name: Build project

on:
  push:
    branches: [main]

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Docker Login
        run: echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u ${{github.actor}} --password-stdin
      - name: Push image
        run: |
          docker build . --tag ghcr.io/derkoe/renovate-hi-test:latest
          docker push ghcr.io/derkoe/renovate-hi-test:latest
